//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaudeTracker.Localization {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClaudeTracker.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        // App
        public static string AppName => ResourceManager.GetString("AppName", resourceCulture) ?? "";
        public static string AppDescription => ResourceManager.GetString("AppDescription", resourceCulture) ?? "";

        // Common
        public static string OK => ResourceManager.GetString("OK", resourceCulture) ?? "";
        public static string Cancel => ResourceManager.GetString("Cancel", resourceCulture) ?? "";
        public static string Save => ResourceManager.GetString("Save", resourceCulture) ?? "";
        public static string Delete => ResourceManager.GetString("Delete", resourceCulture) ?? "";
        public static string Settings => ResourceManager.GetString("Settings", resourceCulture) ?? "";
        public static string Quit => ResourceManager.GetString("Quit", resourceCulture) ?? "";
        public static string Refresh => ResourceManager.GetString("Refresh", resourceCulture) ?? "";
        public static string RefreshNow => ResourceManager.GetString("RefreshNow", resourceCulture) ?? "";

        // Tray
        public static string TrayTooltip => ResourceManager.GetString("TrayTooltip", resourceCulture) ?? "";
        public static string TrayQuit => ResourceManager.GetString("TrayQuit", resourceCulture) ?? "";

        // Usage
        public static string SessionUsage => ResourceManager.GetString("SessionUsage", resourceCulture) ?? "";
        public static string WeeklyUsage => ResourceManager.GetString("WeeklyUsage", resourceCulture) ?? "";
        public static string OpusUsage => ResourceManager.GetString("OpusUsage", resourceCulture) ?? "";
        public static string SonnetUsage => ResourceManager.GetString("SonnetUsage", resourceCulture) ?? "";
        public static string OverageCost => ResourceManager.GetString("OverageCost", resourceCulture) ?? "";
        public static string APICredits => ResourceManager.GetString("APICredits", resourceCulture) ?? "";
        public static string Resetting => ResourceManager.GetString("Resetting", resourceCulture) ?? "";
        public static string ResetsIn => ResourceManager.GetString("ResetsIn", resourceCulture) ?? "";
        public static string NoCredentials => ResourceManager.GetString("NoCredentials", resourceCulture) ?? "";
        public static string OpenSettingsHint => ResourceManager.GetString("OpenSettingsHint", resourceCulture) ?? "";

        // General Settings
        public static string RefreshInterval => ResourceManager.GetString("RefreshInterval", resourceCulture) ?? "";
        public static string Startup => ResourceManager.GetString("Startup", resourceCulture) ?? "";
        public static string Notifications => ResourceManager.GetString("Notifications", resourceCulture) ?? "";
        public static string TimeAndDisplay => ResourceManager.GetString("TimeAndDisplay", resourceCulture) ?? "";
        public static string ResetTimeFormat => ResourceManager.GetString("ResetTimeFormat", resourceCulture) ?? "";
        public static string TimeFormat => ResourceManager.GetString("TimeFormat", resourceCulture) ?? "";
        public static string RemainingTime => ResourceManager.GetString("RemainingTime", resourceCulture) ?? "";
        public static string ResetTime => ResourceManager.GetString("ResetTime", resourceCulture) ?? "";
        public static string Both => ResourceManager.GetString("Both", resourceCulture) ?? "";
        public static string LaunchAtLogin => ResourceManager.GetString("LaunchAtLogin", resourceCulture) ?? "";
        public static string AutoStartSession => ResourceManager.GetString("AutoStartSession", resourceCulture) ?? "";
        public static string CheckOverageLimit => ResourceManager.GetString("CheckOverageLimit", resourceCulture) ?? "";
        public static string EnableNotifications => ResourceManager.GetString("EnableNotifications", resourceCulture) ?? "";
        public static string AlertAt75 => ResourceManager.GetString("AlertAt75", resourceCulture) ?? "";
        public static string AlertAt90 => ResourceManager.GetString("AlertAt90", resourceCulture) ?? "";
        public static string AlertAt95 => ResourceManager.GetString("AlertAt95", resourceCulture) ?? "";
        public static string SaveChanges => ResourceManager.GetString("SaveChanges", resourceCulture) ?? "";
        public static string SendTestAlert => ResourceManager.GetString("SendTestAlert", resourceCulture) ?? "";

        // Settings Tabs
        public static string PersonalUsage => ResourceManager.GetString("PersonalUsage", resourceCulture) ?? "";
        public static string APIBilling => ResourceManager.GetString("APIBilling", resourceCulture) ?? "";
        public static string CLIAccount => ResourceManager.GetString("CLIAccount", resourceCulture) ?? "";
        public static string Appearance => ResourceManager.GetString("Appearance", resourceCulture) ?? "";
        public static string General => ResourceManager.GetString("General", resourceCulture) ?? "";
        public static string Profiles => ResourceManager.GetString("Profiles", resourceCulture) ?? "";
        public static string Language => ResourceManager.GetString("Language", resourceCulture) ?? "";
        public static string About => ResourceManager.GetString("About", resourceCulture) ?? "";

        // Icon Styles
        public static string IconStyleBattery => ResourceManager.GetString("IconStyleBattery", resourceCulture) ?? "";
        public static string IconStyleProgressBar => ResourceManager.GetString("IconStyleProgressBar", resourceCulture) ?? "";
        public static string IconStylePercentage => ResourceManager.GetString("IconStylePercentage", resourceCulture) ?? "";
        public static string IconStyleRing => ResourceManager.GetString("IconStyleRing", resourceCulture) ?? "";
        public static string IconStyleCompact => ResourceManager.GetString("IconStyleCompact", resourceCulture) ?? "";

        // Notifications
        public static string UsageAlert => ResourceManager.GetString("UsageAlert", resourceCulture) ?? "";
        public static string SessionAutoStarted => ResourceManager.GetString("SessionAutoStarted", resourceCulture) ?? "";
        public static string UsageAtPercent => ResourceManager.GetString("UsageAtPercent", resourceCulture) ?? "";

        // Status
        public static string StatusSafe => ResourceManager.GetString("StatusSafe", resourceCulture) ?? "";
        public static string StatusModerate => ResourceManager.GetString("StatusModerate", resourceCulture) ?? "";
        public static string StatusCritical => ResourceManager.GetString("StatusCritical", resourceCulture) ?? "";

        // Errors
        public static string ConnectionFailed => ResourceManager.GetString("ConnectionFailed", resourceCulture) ?? "";
        public static string InvalidSessionKey => ResourceManager.GetString("InvalidSessionKey", resourceCulture) ?? "";
        public static string Unauthorized => ResourceManager.GetString("Unauthorized", resourceCulture) ?? "";
        public static string RateLimited => ResourceManager.GetString("RateLimited", resourceCulture) ?? "";
        public static string ServerError => ResourceManager.GetString("ServerError", resourceCulture) ?? "";
    }
}
